version: '2.4'

services:
  app1:
    build: ./app1
    image: app1:latest
    ports:
      - "1081:80"
    restart: unless-stopped
  
  app2:
    build: ./app2
    image: app2:latest
    ports:
      - "1082:80"
    restart: unless-stopped
  
  app3:
    build: ./app3
    image: app3:latest
    ports:
      - "1083:80"
    restart: unless-stopped
